# http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: required
dist: trusty
# The next line of code is used for old image - will be valid till September 1st, 2017 and should be removed after (https://blog.travis-ci.com/2017-06-21-trusty-updates-2017-Q2-launch)
group: deprecated-2017Q2

# http://docs.travis-ci.com/user/languages/javascript-with-nodejs/
language: node_js
node_js:
  - "6"
  - "7"

# http://docs.travis-ci.com/user/gui-and-headless-browsers
before_install:
 - cd gserver/

install:
  - npm install

# http://docs.travis-ci.com/user/pull-requests/
script:
  - npm test
